-
  name: Multi-Media Marketing Plan
  image: /assets/images/product/image1.jpg
  description: A multifaceted strategy that involves both the community and local businesses
  url: marketing-plan
  viewport: max-width: 500px;
-
