-
  name: product1
  image: /assets/images/Product/image1.png
  description: FXRaven Multi-Media Marketing Plan.
  url: /path/to/product1
-
  name: product2
  image: /path/to/image2.jpg
  description: This is the second product.
  url: /path/to/product2
